### ISSUE TITLE
Not all required courses satisfied in schedule

### ISSUE THREAD

**Issue by oatmealproblem** [NorseCourse/NorseCourse-Backend#15]
I made the following query:

```
https://norsecourse.com:5000/api/schedules?requiredCourses=479,481,511&numCourses=4&requiredGenEds=Hist
```

Many (all?) of the schedules returned had only three sections, none of which satisfied course 511 (anthro 103)

**Comment by GrantFBarnes** [comment]
course 479,  ACCTG-354-A is taught 12:15-13:15  MWF, and so is 511, anthro 103.  Because they each only have one section and they are in direct conflict with each other, it only took one.  Would you rather have the api return nothing? Let me know if I should make changes.
